version: "3.7"

services:
  database:
    image: postgres
    volumes:
      - ./code_test_schema.sql:/docker-entrypoint-initdb.d/code_test_schema.sql
    environment:
      - POSTGRES_DB=codetest
      - POSTGRES_USER=codetest
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -U codetest
      interval: 5s
      timeout: 1s
      retries: 3
    ports:
      - 5432:5432

  app:
    image: app
    build: src
    command: ["./main.py"]
    volumes:
      - ./data:/data
    depends_on:
      - database
  
  pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:6.12
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data:
